CREATE TABLE Distance (id BIGINT NOT NULL, distance INTEGER, fromLat DOUBLE, fromLng DOUBLE, toLat DOUBLE, toLng DOUBLE, PRIMARY KEY (id)) ENGINE = innodb;
CREATE TABLE District (id INTEGER NOT NULL, ASSISTANT_HOUSEHOLD VARCHAR(255), LEADER_HOUSEHOLD VARCHAR(255), PRIMARY KEY (id)) ENGINE = innodb;
CREATE TABLE Member (household VARCHAR(255) NOT NULL, address VARCHAR(255), auto BIT, city VARCHAR(255), district INTEGER, email VARCHAR(255), lat DOUBLE, lng DOUBLE, phone VARCHAR(255), ST VARCHAR(255), zip VARCHAR(255), PRIMARY KEY (household)) ENGINE = innodb;
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID)) ENGINE = innodb;
CREATE INDEX I_DSTRICT_ASSISTANT ON District (ASSISTANT_HOUSEHOLD);
CREATE INDEX I_DSTRICT_LEADER ON District (LEADER_HOUSEHOLD);
